# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'Student.ui'
#
# Created by: PyQt5 UI code generator 5.9.2
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_Xbox(object):
    def setupUi(self, Xbox):
        Xbox.setObjectName("Xbox")
        Xbox.resize(460, 470)
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap("../../收藏夹/iCloud Photos/Downloads/2019/IMG_0574.PNG"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        Xbox.setWindowIcon(icon)
        self.DIDEdit = QtWidgets.QLineEdit(Xbox)
        self.DIDEdit.setGeometry(QtCore.QRect(80, 275, 161, 21))
        self.DIDEdit.setClearButtonEnabled(True)
        self.DIDEdit.setObjectName("DIDEdit")
        self.MIDEdit = QtWidgets.QLineEdit(Xbox)
        self.MIDEdit.setGeometry(QtCore.QRect(80, 313, 161, 21))
        self.MIDEdit.setClearButtonEnabled(True)
        self.MIDEdit.setObjectName("MIDEdit")
        self.cancelButton = QtWidgets.QPushButton(Xbox)
        self.cancelButton.setGeometry(QtCore.QRect(170, 380, 71, 28))
        self.cancelButton.setObjectName("cancelButton")
        self.label_2 = QtWidgets.QLabel(Xbox)
        self.label_2.setGeometry(QtCore.QRect(25, 98, 41, 16))
        self.label_2.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label_2.setObjectName("label_2")
        self.DorEdit = QtWidgets.QLineEdit(Xbox)
        self.DorEdit.setGeometry(QtCore.QRect(80, 174, 161, 21))
        self.DorEdit.setClearButtonEnabled(True)
        self.DorEdit.setObjectName("DorEdit")
        self.label = QtWidgets.QLabel(Xbox)
        self.label.setGeometry(QtCore.QRect(25, 60, 41, 16))
        self.label.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label.setObjectName("label")
        self.label_5 = QtWidgets.QLabel(Xbox)
        self.label_5.setGeometry(QtCore.QRect(25, 275, 45, 16))
        self.label_5.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label_5.setObjectName("label_5")
        self.msg = QtWidgets.QLabel(Xbox)
        self.msg.setGeometry(QtCore.QRect(40, 17, 201, 16))
        self.msg.setObjectName("msg")
        self.label_4 = QtWidgets.QLabel(Xbox)
        self.label_4.setGeometry(QtCore.QRect(25, 174, 41, 16))
        self.label_4.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label_4.setObjectName("label_4")
        self.SnameEdit = QtWidgets.QLineEdit(Xbox)
        self.SnameEdit.setGeometry(QtCore.QRect(80, 98, 161, 21))
        self.SnameEdit.setClearButtonEnabled(True)
        self.SnameEdit.setObjectName("SnameEdit")
        self.label_6 = QtWidgets.QLabel(Xbox)
        self.label_6.setGeometry(QtCore.QRect(0, 313, 81, 20))
        self.label_6.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label_6.setObjectName("label_6")
        self.nanButton = QtWidgets.QRadioButton(Xbox)
        self.nanButton.setGeometry(QtCore.QRect(100, 137, 41, 19))
        self.nanButton.setObjectName("nanButton")
        self.label_3 = QtWidgets.QLabel(Xbox)
        self.label_3.setGeometry(QtCore.QRect(25, 136, 41, 16))
        self.label_3.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label_3.setObjectName("label_3")
        self.nvButton = QtWidgets.QRadioButton(Xbox)
        self.nvButton.setGeometry(QtCore.QRect(170, 137, 41, 19))
        self.nvButton.setObjectName("nvButton")
        self.okButton = QtWidgets.QPushButton(Xbox)
        self.okButton.setGeometry(QtCore.QRect(80, 380, 71, 28))
        self.okButton.setObjectName("okButton")
        self.SIDEdit = QtWidgets.QLineEdit(Xbox)
        self.SIDEdit.setGeometry(QtCore.QRect(80, 60, 161, 21))
        self.SIDEdit.setReadOnly(False)
        self.SIDEdit.setClearButtonEnabled(True)
        self.SIDEdit.setObjectName("SIDEdit")
        self.label_8 = QtWidgets.QLabel(Xbox)
        self.label_8.setGeometry(QtCore.QRect(0, 220, 81, 16))
        self.label_8.setObjectName("label_8")
        self.isHethdayEdit = QtWidgets.QLineEdit(Xbox)
        self.isHethdayEdit.setGeometry(QtCore.QRect(80, 220, 161, 21))
        self.isHethdayEdit.setObjectName("isHethdayEdit")
        self.ishethEdit = QtWidgets.QLineEdit(Xbox)
        self.ishethEdit.setGeometry(QtCore.QRect(80, 250, 161, 21))
        self.ishethEdit.setObjectName("ishethEdit")
        self.label_9 = QtWidgets.QLabel(Xbox)
        self.label_9.setGeometry(QtCore.QRect(10, 250, 72, 15))
        self.label_9.setObjectName("label_9")

        self.retranslateUi(Xbox)
        QtCore.QMetaObject.connectSlotsByName(Xbox)

    def retranslateUi(self, Xbox):
        _translate = QtCore.QCoreApplication.translate
        Xbox.setWindowTitle(_translate("Xbox", "学生信息盒"))
        self.cancelButton.setText(_translate("Xbox", "取消"))
        self.label_2.setText(_translate("Xbox", "姓名"))
        self.label.setText(_translate("Xbox", "学号"))
        self.label_5.setText(_translate("Xbox", "宿舍号"))
        self.msg.setText(_translate("Xbox", "提示信息"))
        self.label_4.setText(_translate("Xbox", "楼号"))
        self.label_6.setText(_translate("Xbox", "工作人员ID"))
        self.nanButton.setText(_translate("Xbox", "男"))
        self.label_3.setText(_translate("Xbox", "性别"))
        self.nvButton.setText(_translate("Xbox", "女"))
        self.okButton.setText(_translate("Xbox", "确定"))
        self.label_8.setText(_translate("Xbox", "健康码天数"))
        self.label_9.setText(_translate("Xbox", "核酸情况"))

